services:
  subscriptionService:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SERVER_PORT: 8080

  database:
    image: postgres:17.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SubscriptionService
      POSTGRES_USER: postgres
    volumes:
      - /var/lib/postgresql/data:/subscription-data