drop table if exists subscriptions;
drop table if exists users;


create table subscriptions (id bigint generated by default as identity (START WITH 11 INCREMENT BY 1), user_id bigint, digital_service varchar(255) check (digital_service in ('YOUTUBE_PREMIUM','YANDEX_PLUS','VK_MUSIC','NETFLIX','HBO_MAX','SPOTIFY','AMAZON_PRIME','APPLE_TV_PLUS')), primary key (id));
create table users (id bigint generated by default as identity (START WITH 6 INCREMENT BY 1), email varchar(255), password varchar(255), username varchar(255), primary key (id));
alter table if exists subscriptions add constraint FKhro52ohfqfbay9774bev0qinr foreign key (user_id) references users;

create unique index userIdWith on subscriptions(user_id, digital_service)